Nuance couleurs
Etienne-Perinet/SherbrookeGameJam pull request #27
Opened 2022-04-21 03:31 UTC by Capucinoxx

afficher le feu follet de la bonne couleur selon le triangle de Maxell 
![image](https://user-images.githubusercontent.com/42392217/164366483-ae1f3cfc-e3d9-4a7a-845d-d667a58544dd.png)

2022-04-21 03:44 UTC, Capucinoxx commented
@jactymilena note, les fichiers relatif à la healthbar ont éeé changé de répertoire, regarder si cela n'a pas impacté les prefabs :)

2022-04-22 19:32 UTC, Capucinoxx commented on Assets/Scripts/HealthBar/HealthBar.cs
> +    );
on ne voudrait faire bouger le point dans le triangle seulement lorsque la partie n'est pas terminée. Sinon cela fait un effet visuel que le point peut sortir du triangle

```suggestion
    bool isEnd = !IsPointInTriangle(newPos + initialPos);
    if (!isEnd)
    {
        cursor.localPosition = newPos;
        cursor.position = (Vector2)cursor.position + initialPos;
    }

    return new HealthBarResponse(
      colors.AppendColor(color, val / 4), 
      isEnd,
    );
```

2022-04-22 20:06 UTC, jactymilena commented
> @jactymilena note, les fichiers relatif à la healthbar ont éeé changé de répertoire, regarder si cela n'a pas impacté les prefabs :)
Les prefabs associés à la health bar ont été corrigés.

2022-04-24 03:49 UTC, Capucinoxx commented on Assets/Scripts/HealthBar/HealthBar.cs
> +    );
done

2022-04-24 14:51 UTC, jactymilena requested changes
Il y a avait 3 scripts pareils associés à la healt bar, ça l'a été corrigé. Ne pas oublier de faire un pull.

2022-04-24 14:51 UTC, jactymilena commented on Assets/Scripts/Enemy/Enemy.cs
> +    public HealthBarColor enemyType { get; protected set; }
Les propriétés doivent être déclarées avec une majuscule au début.
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/using-properties

2022-04-24 14:51 UTC, jactymilena commented on Assets/Scripts/Enemy/Enemy.cs
> +        FindObjectOfType<GameManager>().DecrementEnemyCount(enemyType);
Selon la doc de Unity, la fonction `FindObjectOfType` est très lente. Donc, stocker le gameObject du GameManager dans une variable serait mieux. 
https://docs.unity3d.com/ScriptReference/Object.FindObjectOfType.html

2022-04-24 14:51 UTC, jactymilena commented on Assets/Scripts/FeuFollet/PlayerInteractions.cs
>              FindObjectOfType<AudioManager>().Play("DamageSound");
Même chose que pour le GameManager, ne pas utiliser FindObjectOfType, utiliser une variable à la place.

2022-04-24 14:51 UTC, jactymilena commented on Assets/Scripts/FeuFollet/PlayerInteractions.cs
> +    [SerializeField] private HealthBar healthBar;
Mettre un tag sur la health bar dans l'inspecteur et aller chercher l'object en utilisant la fonction FindWithTag. Enlever le SerializeField par la suite.
https://docs.unity3d.com/ScriptReference/GameObject.FindWithTag.html

2022-04-24 14:51 UTC, jactymilena commented on Assets/Scripts/FeuFollet/PlayerInteractions.cs
> +            HealthBarResponse response = healthBar.AddColor(enemyColor, enemyObject.CollisionDamage);
enemyObject.enemyType pourrait être passé directement dans AddColor.

2022-04-24 14:51 UTC, jactymilena commented on Assets/Scripts/FeuFollet/PlayerInteractions.cs
>          FindObjectOfType<GameManager>().EndGame();
Utiliser la fonction FindWithTag à la place ou utiliser une variable.

2022-04-24 14:51 UTC, jactymilena commented on Assets/Scripts/HealthBar/HealthBar.cs
> +  private ColorsVec colors;
Avoir des spaces uniformes.

2022-04-24 14:51 UTC, jactymilena commented on Assets/Scripts/HealthBar/HealthBarResponse.cs
> +  public bool isEnd { get; }
Les propriétés d'une classe doivent commencer par une majuscule.

2022-04-24 14:53 UTC, jactymilena commented on Assets/Scripts/FeuFollet/PlayerInteractions.cs
> +    [SerializeField] private HealthBar healthBar;
(Aller le chercher dans le Awake)

2022-04-25 01:41 UTC, merged