[feat] - maintenir le click permet de tirer à un débit de 3 balles se…
Etienne-Perinet/SherbrookeGameJam pull request #30
Opened 2022-04-22 01:59 UTC by Capucinoxx

maintient du click de souris permet de tirer à une vitesse de 1/0.35 balles par seconde (un peu moins de 3 balles). On peut toujours continuer de spam clique et cela laissera la vitesse du clique de la personne

https://user-images.githubusercontent.com/42392217/164581403-7e452867-7105-40e3-a5ed-6c2c1adf75e2.mp4

2022-04-24 16:59 UTC, jactymilena requested changes

2022-04-24 16:59 UTC, jactymilena commented on Assets/Scripts/FeuFollet/Shooting.cs
>          FindObjectOfType<AudioManager>().Play("GunSound");
Ne pas utiliser de FindObjectOfType.

2022-04-24 19:51 UTC, LPGeoffroy commented on Assets/Scripts/FeuFollet/Shooting.cs
>          FindObjectOfType<AudioManager>().Play("GunSound");
Pourquoi? @jactymilena

2022-04-24 20:42 UTC, Capucinoxx commented on Assets/Scripts/FeuFollet/Shooting.cs
>          FindObjectOfType<AudioManager>().Play("GunSound");
@LPGeoffroy 
https://answers.unity.com/questions/452946/which-unity-functions-are-generally-slowbad-for-pe.html

2022-05-01 13:26 UTC, jactymilena approved these changes

2022-05-01 13:30 UTC, merged