Difficulté des ennemis
Etienne-Perinet/SherbrookeGameJam pull request #32
Opened 2022-04-25 19:50 UTC by jactymilena

-  Les ennemis ont des vitesses différentes qui augmentent selon un pourcentage exponentiel avec le temps de jeu.

2022-04-25 23:30 UTC, Capucinoxx requested changes

2022-04-25 23:30 UTC, Capucinoxx commented on Assets/Scripts/Enemy/Enemy.cs
> +    public float speed = 2f;
mettre l'attribut protected

2022-04-25 23:30 UTC, Capucinoxx commented on Assets/Scripts/Enemy/Enemy.cs
>      private GameManager gameManager;
changer deathAnimation pour être private

2022-04-25 23:41 UTC, jactymilena commented on Assets/Scripts/Enemy/Enemy.cs
>      private GameManager gameManager;
Je pense ça serait mieux de l'effacer puisque la variable ne semble pas être utilisée.

2022-04-27 19:55 UTC, Capucinoxx approved these changes

2022-04-27 23:56 UTC, merged